# Generated by Django 5.1.2 on 2024-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors_Register_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('Experience', models.CharField(blank=True, max_length=200, null=True)),
                ('Password', models.CharField(blank=True, max_length=200, null=True)),
                ('C_password', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
