# Generated by Django 5.1.2 on 2024-12-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0002_mentors_register_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meander_Register_Db',
        ),
    ]
