# Generated by Django 5.1.2 on 2024-12-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0003_delete_meander_register_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors_register_db',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
