# Generated by Django 5.1.2 on 2024-12-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0004_alter_mentors_register_db_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors_register_db',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
