# Generated by Django 5.1.2 on 2024-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0006_alter_mentors_register_db_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors_register_db',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
