# Generated by Django 5.1.2 on 2024-12-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0007_alter_mentors_register_db_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentors_register_db',
            old_name='Password',
            new_name='M_Password',
        ),
    ]
