# Generated by Django 5.1.2 on 2024-12-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0008_rename_password_mentors_register_db_m_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentors_register_db',
            old_name='M_Password',
            new_name='Password',
        ),
    ]
