# Generated by Django 5.1.2 on 2025-01-15 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0009_rename_m_password_mentors_register_db_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Class_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.CharField(blank=True, max_length=200, null=True)),
                ('Course', models.CharField(blank=True, max_length=200, null=True)),
                ('Subject', models.CharField(blank=True, max_length=200, null=True)),
                ('Topic_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Upload_Class', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('Upload_PDF', models.FileField(blank=True, null=True, upload_to='Record_class_Pdfs')),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('Video_Duration', models.DurationField(blank=True, null=True)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
