# Generated by Django 5.1.2 on 2025-01-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0010_record_class_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_class_db',
            name='Mentors_Id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
