# Generated by Django 5.1.2 on 2025-01-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0011_record_class_db_mentors_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors_register_db',
            name='OTP',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
