# Generated by Django 5.1.2 on 2025-01-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0012_mentors_register_db_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_class_db',
            name='Login_Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='record_class_db',
            name='Logout_Time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
