# Generated by Django 5.1.2 on 2025-01-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0014_liveclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveClass',
        ),
    ]
