# Generated by Django 5.1.2 on 2025-01-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0016_liveclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='mentor',
            field=models.CharField(max_length=200),
        ),
    ]
