# Generated by Django 5.1.2 on 2025-01-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0017_alter_liveclass_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclass',
            old_name='mentor',
            new_name='mentor_id',
        ),
    ]
