# Generated by Django 5.1.2 on 2025-01-28 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0018_rename_mentor_liveclass_mentor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='mentor_id',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MentorsApp.mentors_register_db'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='live_start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='topic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_meeting_link',
            field=models.URLField(blank=True, default='https://default.zoom.link', null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_start_url',
            field=models.URLField(blank=True, default='https://default.zoom.startlink', null=True),
        ),
    ]
