# Generated by Django 5.1.2 on 2025-01-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0019_remove_liveclass_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
