# Generated by Django 5.1.2 on 2025-02-05 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorsApp', '0020_alter_liveclass_zoom_meeting_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_Live_Details_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentors_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Exam', models.CharField(blank=True, max_length=200, null=True)),
                ('Course', models.CharField(blank=True, max_length=200, null=True)),
                ('Subject', models.CharField(blank=True, max_length=200, null=True)),
                ('Topic_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Personal_link', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_Time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LiveClass',
        ),
    ]
