# Generated by Django 5.1.2 on 2024-12-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_db',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
