# Generated by Django 5.1.2 on 2024-12-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0002_alter_register_db_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_db',
            old_name='Full_name',
            new_name='Username',
        ),
    ]
