# Generated by Django 5.1.2 on 2024-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0003_rename_full_name_register_db_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_db',
            old_name='C_Password',
            new_name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='register_db',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='register_db',
            name='Username',
        ),
        migrations.AddField(
            model_name='register_db',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
