# Generated by Django 5.1.2 on 2024-12-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0004_rename_c_password_register_db_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_db',
            name='otp',
        ),
        migrations.AddField(
            model_name='register_db',
            name='Confirm_Password',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register_db',
            name='Password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
