# Generated by Django 5.1.2 on 2025-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0005_remove_register_db_otp_register_db_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_db',
            name='OTP',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
