# Generated by Django 5.1.2 on 2025-01-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0006_register_db_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_db',
            old_name='Email',
            new_name='Mentors_Email',
        ),
    ]
