# Generated by Django 5.1.2 on 2025-01-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0007_rename_email_register_db_mentors_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_db',
            old_name='Mentors_Email',
            new_name='Email',
        ),
    ]
