# Generated by Django 5.1.2 on 2025-01-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0009_rename_email_register_db_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_db',
            old_name='Student_Email',
            new_name='Email',
        ),
    ]
