# Generated by Django 5.1.2 on 2025-01-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0010_rename_student_email_register_db_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_db',
            old_name='Email',
            new_name='User_Email',
        ),
    ]
