# Generated by Django 5.1.2 on 2025-02-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentsApp', '0012_chatgroup_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
