# Generated by Django 5.1.2 on 2024-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='Exam_Images')),
            ],
        ),
    ]
