# Generated by Django 5.1.2 on 2024-11-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_remove_course_db_category_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_db',
            name='End_date',
        ),
        migrations.RemoveField(
            model_name='course_db',
            name='Start_Date',
        ),
    ]
