# Generated by Django 5.1.2 on 2024-11-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_remove_course_db_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Subject_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
