# Generated by Django 5.1.2 on 2024-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_subject_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_db',
            name='Subject_Images',
            field=models.ImageField(blank=True, null=True, upload_to='Subject_Images'),
        ),
    ]
