# Generated by Django 5.1.2 on 2024-11-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_subject_db_subject_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_db',
            name='Subject_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
