# Generated by Django 5.1.2 on 2024-11-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_subject_db_subject_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_db',
            name='Old_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject_db',
            name='Old_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
