# Generated by Django 5.1.2 on 2025-01-21 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_course_db_old_fees_subject_db_old_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField()),
                ('quantity_sold', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.course_db')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField()),
                ('quantity_sold', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.subject_db')),
            ],
        ),
    ]
