# Generated by Django 5.1.2 on 2024-11-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_register_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_Db',
        ),
    ]
