# Generated by Django 5.1.2 on 2025-01-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Course_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Course_fees', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
