# Generated by Django 5.1.2 on 2025-01-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Db',
        ),
    ]
