# Generated by Django 5.1.2 on 2025-01-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
