# Generated by Django 5.1.2 on 2025-01-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_DB',
        ),
    ]
