# Generated by Django 5.1.2 on 2025-01-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_DB',
        ),
    ]
