# Generated by Django 5.1.2 on 2025-01-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Payment_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Course_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Course_Fees', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
