# Generated by Django 5.1.2 on 2025-01-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0010_subject_payment_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_payment_db',
            old_name='Course_Fees',
            new_name='Subject_Fees',
        ),
        migrations.RenameField(
            model_name='subject_payment_db',
            old_name='Course_Name',
            new_name='Subject_Name',
        ),
    ]
