# Generated by Django 5.1.2 on 2025-01-27 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0011_rename_course_fees_subject_payment_db_subject_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Comments_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_User', models.CharField(blank=True, max_length=200, null=True)),
                ('C_Cours_Name', models.EmailField(blank=True, max_length=200, null=True)),
                ('C_Comment', models.CharField(blank=True, max_length=200, null=True)),
                ('C_Date', models.DateField(default=datetime.date.today)),
                ('C_Time', models.TimeField(default=datetime.time)),
            ],
        ),
    ]
