# Generated by Django 5.1.2 on 2025-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0012_course_comments_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_comments_db',
            name='C_Time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
