# Generated by Django 5.1.2 on 2025-01-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0015_chatgroup_students_alter_chatgroup_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='students',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='course_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.chatgroup'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=200),
        ),
    ]
