# Generated by Django 5.1.2 on 2025-01-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0016_remove_chatgroup_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='students',
            field=models.ManyToManyField(related_name='chat_groups', to='CourseApp.payment_db'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CourseApp.chatgroup'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseApp.payment_db'),
        ),
    ]
