# Generated by Django 5.1.2 on 2025-01-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0017_chatgroup_students_alter_chatgroup_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
