# Generated by Django 5.1.2 on 2025-01-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0018_remove_message_group_remove_message_sender_and_more'),
    ]

    operations = [
    ]
