# Generated by Django 5.1.2 on 2025-01-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0019_auto_20250129_0053'),
    ]

    operations = [
    ]
