# Generated by Django 5.1.2 on 2025-01-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0023_group_message_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
