# Generated by Django 5.1.2 on 2025-01-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0024_remove_message_group_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_payment_db',
            old_name='Email',
            new_name='Subject_Email',
        ),
    ]
